### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by jaydenseric** [trevorblades/countries#33]
<img width="686" alt="Screen Shot 2021-07-17 at 11 59 07 am" src="https://user-images.githubusercontent.com/1754873/126021999-18fee561-9862-474e-a0ee-c7b44b299064.png">

**Comment by jaydenseric** [comment]
Now it's back up. What's going on?

**Comment by jaydenseric** [comment]
For a while just the explorer was working, but not the actual API:

<img width="985" alt="Screen Shot 2021-07-17 at 12 02 26 pm" src="https://user-images.githubusercontent.com/1754873/126022069-02e3af84-5c35-4766-87fc-b170f28bfc11.png">

**Comment by trevorblades** [comment]
@jaydenseric this could be due to some testing I was doing using different hosting providers and changing the DNS for this URL multiple times a couple weeks ago. You may have had cached DNS pointing you to the wrong place at some point.

I've just switched my hosting from a paid Heroku dyno to fly.io and I expect this to result in much more stable and fast service. Let me know if you notice anything weird happening again and I'd be happy to investigate further! 🙂
